var catalog = [
    {
        _id: "5f40a6baac77a903d8f682c6",
        price: 12.32,
        stock: 13,
        title: "Chaga",
        image: "chaga.webp",
        discount: 5,
        category: "mushrooms",
      },
      {
        _id: "5f40a6ba41d9e5044ced586c",
        price: 22.71,
        stock: 21,
        title: "Reshi",
        image: "/img/reshi.jpeg",
        discount: 10,
        category: "mushrooms",
      },
      {
        _id: "5f40a6baa9e6e22fa1d5fac4",
        price: 32.0,
        stock: 20,
        title: "Lion's mane",
        image: "lions mane",
        discount: 0,
        category: "mushrooms",
      },
      {
        _id: "5f40a6baac77a903d8f682c6",
        price: 12.32,
        stock: 13,
        title: "Turkettail",
        image: "",
        discount: 5,
        category: "mushrooms",
      },
      {
        _id: "5f40a6ba41d9e5044ced586c",
        price: 22.71,
        stock: 21,
        title: "Maitake",
        image: "",
        discount: 10,
        category: "mushrooms",
      },
      {
        _id: "5f40a6baa9e6e22fa1d5fac4",
        price: 32.0,
        stock: 20,
        title: "Morel",
        image: "",
        discount: 0,
        category: "mushrooms",
      },
      {
        _id: "5f40a6baac77a903d8f682c6",
        price: 12.32,
        stock: 13,
        title: "Shiitake",
        image: "",
        discount: 5,
        category: "mushrooms",
      },
      {
        _id: "5f40a6ba41d9e5044ced586c",
        price: 22.71,
        stock: 21,
        title: "Cordyceps",
        image: "",
        discount: 10,
        category: "mushrooms",
      },
      {
        _id: "5f40a6baa9e6e22fa1d5fac4",
        price: 32.0,
        stock: 20,
        title: "Agarikon",
        image: "",
        discount: 0,
        category: "mushrooms",
      },
      {
        _id: "5f40a6baa9e6e22fa1d5fac4",
        price: 32.0,
        stock: 20,
        title: "Goldenteacher",
        image: "",
        discount: 0,
        category: "mushrooms",
      }
    ]